version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: lern-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=lern

  redis:
    image: redis:7.0-alpine
    container_name: lern-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
